[default]
timeout = 300
filters = ["Onder bod", "Verkocht", "VERKOCHT"]
onFail = "stale"
entrySelector = ".aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"
waitUntilSelector = ".column"

[thijssenmakelaars]
title = "Paul Thijssen makelaars"
url = "https://www.thijssenmakelaars.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/2+kamers/"
timeout = 600

[immo030]
title = "IMMO 030 makelaars"
url = "https://www.immo-030.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/2+kamers/"

[ansdewijn]
title = "Ans de Wijn woningen"
url = "https://www.ansdewijnwoningen.nl/aanbod/woningaanbod/beschikbaar/-400000/koop/"

[pauldijkstra]
title = "Paul Dijkstra makelaars"
url = "https://www.leefengeniet.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/-400000/koop/provincie-Utrecht/"

[nu]
title = "NU makelaardij"
url = "https://www.nu-makelaardij.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/-400000/koop/provincie-Utrecht/"

[clemens]
title = "Clemens de Korte makelaardij"
url = "https://www.clemensdekorte.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/3+kamers/"
timeout = 600

[nijland]
title = "Nijland Makelaars"
url = "https://www.nijland.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/aantal-80/3+kamers/"
filters = ["Onder bod", "Verkocht"]
timeout = 600

[leuk]
title = "leuk! makelaars"
url = "https://www.leuk-makelaars.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/provincie-Utrecht/"
timeout = 420

[hanasbei]
title = "Hanasbei makelaardij"
url = "https://www.hanasbeimakelaardij.nl/aanbod/woningaanbod/beschikbaar/-400000/koop/"

[gradajager]
title = "Grada Jager makelaardij"
url = "https://www.gradajager.nl/aanbod/woningaanbod/UTRECHT/70+woonopp/-400000/koop/3+kamers/"

[quist]
title = "Quist makelaardij"
url = "https://www.quistmakelaardij.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/3+kamers/"

[era]
title = "ERA Makelaardij Utrecht"
url = "https://www.makelaardijutrecht.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"

[van-doorn]
title = "Van Doorn Makelaardij Utrecht"
url = "https://www.van-doorn.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"

[patist]
title = "Patist Makelaardij Utrecht"
url = "https://www.patistmakelaardij.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"

[sino]
title = "Si-No Makelaars"
url = "https://www.si-no.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"

[wvo]
title = "WVO makelaars"
url = "https://www.wvo.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"

[roeldemakelaar]
title = "Roel de makelaar"
url = "https://www.roeldemakelaar.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"

[renkemajansen]
title = "Renkema & Jansen Makelaars"
url = "https://www.renkemajansen.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/70+woonopp/-400000/koop/2+kamers/"